<?php


namespace App\Form;


use App\data\SearchData;
use App\Entity\Sujet;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SearchForm extends AbstractType
{
   public function buildForm(FormBuilderInterface $builder, array $options)
   {
       $builder->add('q',TextType::class,[
           'label'=>false,
           'required'=>false,
           'attr'=>[
               'placeholder'=>'chercher un sujet',



           ]
       ]);



       //   parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
   }

    public function configureOptions(OptionsResolver $resolver)
    {
     //   parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    $resolver->setDefaults([
        'data_class'=>SearchData::class,'method'=>'GET','csrf_protection'=>false
    ]);


    }
    public function getBlockPrefix()
    {
        return '';
     //   return parent::getBlockPrefix(); // TODO: Change the autogenerated stub

    }

}